-- Rifts Terminal Expansion Schema

-- 1. BOUNTIES TABLE
create table public.bounties (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  type text,
  reward integer default 0,
  last_seen text,
  status text check (status in ('WANTED DEAD', 'WANTED ALIVE', 'CAPTURE ONLY', 'Observe')) default 'WANTED ALIVE',
  image_url text
);

-- 2. MISSIONS TABLE
create table public.missions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  reward integer default 0,
  difficulty text check (difficulty in ('LOW', 'MED', 'HIGH', 'EXTREME')),
  faction text default 'Coalition States',
  expires_at timestamp with time zone
);

-- 3. MARKET ITEMS TABLE
create table public.market_items (
  id bigint generated by default as identity primary key,
  name text not null,
  stock integer default 0,
  price integer default 0,
  is_illegal boolean default false,
  category text
);

-- 4. INTEL REPORTS TABLE
create table public.intel_reports (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  body text,
  author text default 'Command'
);

-- 5. SECURE COMMS TABLE
create table public.secure_messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  sender text not null,
  recipient_tag_id text references public.credsticks(tag_id),
  subject text,
  body text,
  is_encrypted boolean default false,
  is_read boolean default false
);

-- ENABLE RLS (Row Level Security) - Optional but recommended
alter table public.bounties enable row level security;
alter table public.missions enable row level security;
alter table public.market_items enable row level security;
alter table public.intel_reports enable row level security;
alter table public.secure_messages enable row level security;

-- Create policies (modify as needed)
-- Example: Allow everyone to read bounties
create policy "Enable read access for all users" on public.bounties for select using (true);
